In [1]:
import numpy as np
import pandas as pd
from IPython.core.display import display
from matplotlib import pyplot as plt

pd.set_option('display.max_columns', None)
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBRFClassifier
from sklearn.dummy import DummyClassifier
from ConstantClassifier import ConstantClassifier
import configs
import warnings
import classifier_utils
import seaborn as sns
warnings.filterwarnings("ignore")

from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_predict, GridSearchCV, validation_curve
from sklearn.impute import SimpleImputer
import math

In [2]:
non_features_columns = ["chunk_id", "line_start", "line_end", "line_separator", "kind_conflict", "url", "project"]
non_features_columns.extend(["project_user", "project_name", "path", "file_name", "sha", "leftsha", "rightsha", "basesha"])

In [3]:
selected_dataset = pd.read_csv("../../data/SELECTED_LABELLED_DATASET.csv")
projects = list(selected_dataset['project'].unique())

In [4]:
df_test = pd.read_csv("../../data/dataset-test.csv")
target_names = sorted(list(df_test['developerdecision'].unique()))
df_na = df_test[df_test.isna().any(axis=1)]

len(df_na) / len(df_test)

0.2530394472142045

# Class distributions

### Normalized (%)

In [5]:
import importlib
importlib.reload(classifier_utils)
class_distribution_normalized = classifier_utils.get_projects_class_distribution(projects, include_overall=True, training=False)

class_distribution_normalized

,Project,Version 1,Version 2,Combination,ConcatenationV1V2,ConcatenationV2V1,Manual,None
0,Ramblurr__Anki-Android,44.10,27.18,8.21,0.51,0.51,19.49,0.00
1,apache__directory-server,44.91,53.29,0.00,0.00,0.00,1.80,0.00
2,android__platform_frameworks_base,66.05,8.95,8.61,3.72,1.18,11.15,0.17
3,freenet__fred,43.08,17.79,20.16,7.91,0.40,10.28,0.40
4,alexo__wro4j,32.46,11.30,27.83,1.45,0.00,25.80,1.16
5,apache__lucene-solr,26.72,22.27,18.22,7.29,1.21,21.05,3.24
6,elastic__elasticsearch,0.00,0.00,0.00,0.00,0.00,0.00,0.00
7,getrailo__railo,27.87,39.34,9.84,9.02,0.00,13.11,0.82
8,atlasapi__atlas,20.00,46.67,10.77,5.64,2.05,13.85,1.03
9,hibernate__hibernate-orm,23.53,18.82,35.29,6.47,0.00,14.12,1.76
10,CloudStack-extras__CloudStack-archive,42.80,18.18,7.95,18.18,1.14,11.36,0.38
11,TeamDev-Ltd__OpenFaces,94.24,1.40,1.12,0.56,0.42,2.25,0.00
12,eucalyptus__eucalyptus,43.32,24.60,9.09,5.35,1.07,15.51,1.07
13,zkoss__zk,56.48,14.35,10.19,1.39,0.93,16.67,0.00
14,eclipse__jetty.project,0.00,0.00,0.00,0.00,0.00,0.00,0.00
15,alkacon__opencms-core,91.43,3.81,0.48,0.95,0.00,3.33,0.00
16,SINTEF-9012__ThingML,92.59,0.41,0.41,0.41,0.00,6.17,0.00
17,apache__accumulo,64.24,17.88,6.64,0.64,0.89,9.45,0.26
18,Unidata__thredds,17.43,72.20,1.24,0.00,0.00,8.71,0.41
19,revolsys__com.revolsys.open,0.00,0.00,0.00,0.00,0.00,0.00,0.00
20,jgralab__jgralab,50.44,37.72,4.82,0.22,0.22,6.58,0.00
21,sebastianbenz__Jnario,99.95,0.00,0.00,0.00,0.00,0.05,0.00
22,CCI-MIT__XCoLab,57.30,14.82,0.66,0.11,0.11,26.99,0.00
23,Overall,66.58,14.86,5.91,2.04,0.41,9.88,0.30

### Count

In [6]:
class_distribution_count = classifier_utils.get_projects_class_distribution(projects, False, include_overall=True, training=False)

class_distribution_count

,Project,Version 1,Version 2,Combination,ConcatenationV1V2,ConcatenationV2V1,Manual,None
0,Ramblurr__Anki-Android,86,53,16,1,1,38,0
1,apache__directory-server,75,89,0,0,0,3,0
2,android__platform_frameworks_base,391,53,51,22,7,66,1
3,freenet__fred,109,45,51,20,1,26,1
4,alexo__wro4j,112,39,96,5,0,89,4
5,apache__lucene-solr,66,55,45,18,3,52,8
6,elastic__elasticsearch,0,0,0,0,0,0,0
7,getrailo__railo,34,48,12,11,0,16,1
8,atlasapi__atlas,39,91,21,11,4,27,2
9,hibernate__hibernate-orm,40,32,60,11,0,24,3
10,CloudStack-extras__CloudStack-archive,113,48,21,48,3,30,1
11,TeamDev-Ltd__OpenFaces,671,10,8,4,3,16,0
12,eucalyptus__eucalyptus,81,46,17,10,2,29,2
13,zkoss__zk,122,31,22,3,2,36,0
14,eclipse__jetty.project,0,0,0,0,0,0,0
15,alkacon__opencms-core,192,8,1,2,0,7,0
16,SINTEF-9012__ThingML,225,1,1,1,0,15,0
17,apache__accumulo,503,140,52,5,7,74,2
18,Unidata__thredds,42,174,3,0,0,21,1
19,revolsys__com.revolsys.open,0,0,0,0,0,0,0
20,jgralab__jgralab,230,172,22,1,1,30,0
21,sebastianbenz__Jnario,2037,0,0,0,0,1,0
22,CCI-MIT__XCoLab,518,134,6,1,1,244,0
23,Overall,5686,1269,505,174,35,844,26

# Classification results

In [7]:
model = RandomForestClassifier(random_state=99, n_jobs=-2, n_estimators=400, max_features=0.3, min_samples_leaf=1)

### Training/validation validation data

Uses 80% of the data with a 10-fold cross-validation to calculate the average accuracy for each project

In [8]:
results = classifier_utils.ProjectsResults(model, projects, non_features_columns)

In [9]:
report = results.get_report_df(include_overall=True)
report

,project,observations,observations (wt NaN),precision,recall,f1-score,accuracy,baseline (majority),improvement
0,CCI-MIT__XCoLab,5512,3757,0.97200,0.9750,0.97300,0.9750,0.57300,0.9420
1,apache__directory-server,845,652,0.93600,0.9390,0.93700,0.9390,0.51200,0.8740
2,jgralab__jgralab,2072,1802,0.86800,0.8700,0.86800,0.8700,0.49100,0.7450
3,CloudStack-extras__CloudStack-archive,1424,1106,0.80000,0.8070,0.80100,0.8070,0.43700,0.6570
4,Unidata__thredds,1154,950,0.91600,0.9220,0.91700,0.9220,0.77700,0.6510
5,apache__accumulo,4113,3148,0.85700,0.8630,0.85900,0.8630,0.63500,0.6250
6,Ramblurr__Anki-Android,892,759,0.72100,0.7430,0.72500,0.7430,0.43900,0.5420
7,getrailo__railo,815,572,0.69500,0.7130,0.70200,0.7130,0.37800,0.5390
8,apache__lucene-solr,1256,974,0.64400,0.6500,0.64400,0.6500,0.26600,0.5230
9,TeamDev-Ltd__OpenFaces,2979,2859,0.96500,0.9680,0.96600,0.9680,0.93800,0.4830
10,zkoss__zk,1087,881,0.77200,0.7870,0.77700,0.7870,0.60200,0.4640
11,freenet__fred,1268,1012,0.66500,0.6730,0.66700,0.6730,0.40400,0.4510
12,hibernate__hibernate-orm,1000,716,0.59300,0.6050,0.59200,0.6050,0.31100,0.4260
13,atlasapi__atlas,1107,782,0.66100,0.6750,0.66300,0.6750,0.44500,0.4150
14,alexo__wro4j,1663,1368,0.57200,0.5840,0.57500,0.5840,0.30700,0.4000
15,android__platform_frameworks_base,3557,2460,0.81200,0.8190,0.81300,0.8190,0.70800,0.3800
16,eucalyptus__eucalyptus,1020,747,0.59700,0.6160,0.60300,0.6160,0.42300,0.3340
17,alkacon__opencms-core,923,840,0.94800,0.9620,0.95500,0.9620,0.94400,0.3190
18,SINTEF-9012__ThingML,1022,977,0.93500,0.9480,0.94100,0.9480,0.93800,0.1640
19,sebastianbenz__Jnario,8298,8173,0.99800,0.9990,0.99900,0.9990,0.99900,0.0000
20,elastic__elasticsearch,1246,0,NaN,NaN,NaN,NaN,NaN,NaN
21,eclipse__jetty.project,1537,0,NaN,NaN,NaN,NaN,NaN,NaN
22,revolsys__com.revolsys.open,991,1,NaN,NaN,NaN,NaN,NaN,NaN
23,Overall,45781,34536,0.79635,0.8059,0.79885,0.8059,0.57635,0.4967

### Test

Uses 80% of the data to train the model and the remaining 20% of the data to test it. 
The accuracy is calculated based on the 20% of the data that the model has never seen during training.

In [10]:
results_test = classifier_utils.ProjectsResults(model, projects, non_features_columns, training=False)

In [11]:
report_test = results_test.get_report_df(include_overall=True)
report_test

,project,observations,observations (wt NaN),precision,recall,f1-score,accuracy,baseline (majority),improvement
0,CCI-MIT__XCoLab,5512,3757,0.97800,0.98000,0.97800,0.98000,0.57300,0.95300
1,apache__directory-server,845,652,0.92200,0.92200,0.92100,0.92200,0.53300,0.83300
2,jgralab__jgralab,2072,1802,0.87700,0.88200,0.87700,0.88200,0.50400,0.76100
3,Unidata__thredds,1154,950,0.90800,0.91300,0.90800,0.91300,0.72200,0.68700
4,CloudStack-extras__CloudStack-archive,1424,1106,0.83000,0.81400,0.81700,0.81400,0.42800,0.67500
5,Ramblurr__Anki-Android,892,759,0.79400,0.81000,0.80000,0.81000,0.44100,0.66100
6,apache__accumulo,4113,3148,0.86300,0.87000,0.86400,0.87000,0.64200,0.63600
7,getrailo__railo,815,572,0.70500,0.70500,0.69500,0.70500,0.39300,0.51400
8,zkoss__zk,1087,881,0.78100,0.78700,0.78100,0.78700,0.56500,0.51100
9,apache__lucene-solr,1256,974,0.61300,0.62300,0.60900,0.62300,0.26700,0.48600
10,android__platform_frameworks_base,3557,2460,0.81200,0.82300,0.81500,0.82300,0.66000,0.47800
11,freenet__fred,1268,1012,0.66700,0.68400,0.67100,0.68400,0.43100,0.44400
12,TeamDev-Ltd__OpenFaces,2979,2859,0.96100,0.96800,0.96400,0.96800,0.94200,0.43900
13,alexo__wro4j,1663,1368,0.60800,0.61700,0.60900,0.61700,0.32500,0.43300
14,hibernate__hibernate-orm,1000,716,0.60800,0.60000,0.60200,0.60000,0.35300,0.38200
15,eucalyptus__eucalyptus,1020,747,0.63200,0.64700,0.62900,0.64700,0.43300,0.37700
16,alkacon__opencms-core,923,840,0.90200,0.94300,0.92200,0.94300,0.91400,0.33300
17,atlasapi__atlas,1107,782,0.59100,0.61500,0.59500,0.61500,0.46700,0.27900
18,SINTEF-9012__ThingML,1022,977,0.92000,0.93400,0.92500,0.93400,0.92600,0.11100
19,sebastianbenz__Jnario,8298,8173,0.99900,1.00000,0.99900,1.00000,1.00000,0.00000
20,elastic__elasticsearch,1246,0,NaN,NaN,NaN,NaN,NaN,NaN
21,eclipse__jetty.project,1537,0,NaN,NaN,NaN,NaN,NaN,NaN
22,revolsys__com.revolsys.open,991,1,NaN,NaN,NaN,NaN,NaN,NaN
23,Overall,45781,34536,0.79855,0.80685,0.79905,0.80685,0.57595,0.49965

# Summary of the results

In [12]:
df_inner = pd.merge(report, report_test, on='project', how='inner', suffixes=('_cv', '_test'))
df = df_inner.filter(regex=("project|accuracy.*|precision_test|recall_test|f1-score_test")).copy()
df = df.rename(columns={"precision_test": "precision", 'recall_test':'recall', 'f1-score_test':'f1-score'})
df['norm._improv.'] = df.apply(lambda x: classifier_utils.get_normalized_improvement(x['accuracy_test'], x['accuracy_cv']), axis=1)
columns = ['project', 'accuracy_cv', 'accuracy_test', 'norm._improv.', 'precision', 'recall', 'f1-score']
df[columns]

,project,accuracy_cv,accuracy_test,norm._improv.,precision,recall,f1-score
0,CCI-MIT__XCoLab,0.9750,0.98000,0.200000,0.97800,0.98000,0.97800
1,apache__directory-server,0.9390,0.92200,-0.018104,0.92200,0.92200,0.92100
2,jgralab__jgralab,0.8700,0.88200,0.092308,0.87700,0.88200,0.87700
3,CloudStack-extras__CloudStack-archive,0.8070,0.81400,0.036269,0.83000,0.81400,0.81700
4,Unidata__thredds,0.9220,0.91300,-0.009761,0.90800,0.91300,0.90800
5,apache__accumulo,0.8630,0.87000,0.051095,0.86300,0.87000,0.86400
6,Ramblurr__Anki-Android,0.7430,0.81000,0.260700,0.79400,0.81000,0.80000
7,getrailo__railo,0.7130,0.70500,-0.011220,0.70500,0.70500,0.69500
8,apache__lucene-solr,0.6500,0.62300,-0.041538,0.61300,0.62300,0.60900
9,TeamDev-Ltd__OpenFaces,0.9680,0.96800,0.000000,0.96100,0.96800,0.96400
10,zkoss__zk,0.7870,0.78700,0.000000,0.78100,0.78700,0.78100
11,freenet__fred,0.6730,0.68400,0.033639,0.66700,0.68400,0.67100
12,hibernate__hibernate-orm,0.6050,0.60000,-0.008264,0.60800,0.60000,0.60200
13,atlasapi__atlas,0.6750,0.61500,-0.088889,0.59100,0.61500,0.59500
14,alexo__wro4j,0.5840,0.61700,0.079327,0.60800,0.61700,0.60900
15,android__platform_frameworks_base,0.8190,0.82300,0.022099,0.81200,0.82300,0.81500
16,eucalyptus__eucalyptus,0.6160,0.64700,0.080729,0.63200,0.64700,0.62900
17,alkacon__opencms-core,0.9620,0.94300,-0.019751,0.90200,0.94300,0.92200
18,SINTEF-9012__ThingML,0.9480,0.93400,-0.014768,0.92000,0.93400,0.92500
19,sebastianbenz__Jnario,0.9990,1.00000,1.000000,0.99900,1.00000,0.99900
20,elastic__elasticsearch,NaN,NaN,NaN,NaN,NaN,NaN
21,eclipse__jetty.project,NaN,NaN,NaN,NaN,NaN,NaN
22,revolsys__com.revolsys.open,NaN,NaN,NaN,NaN,NaN,NaN
23,Overall,0.8059,0.80685,0.004894,0.79855,0.80685,0.79905

# Results per class

In [13]:
baseline_combination = ConstantClassifier('Combination')
baseline_version1 = ConstantClassifier('Version 1')
baseline_version2 = ConstantClassifier('Version 2')
baseline_concatenationv1v2 = ConstantClassifier('ConcatenationV1V2')
baseline_concatenationv2v1 = ConstantClassifier('ConcatenationV2V1')
baseline_manual = ConstantClassifier('Manual')
baseline_none = ConstantClassifier('None')
model = RandomForestClassifier(random_state=99, n_jobs=5, n_estimators=100, max_features=0.3, min_samples_leaf=1)
models = [baseline_combination, baseline_version1, baseline_version2,
          baseline_concatenationv1v2, baseline_concatenationv2v1, baseline_manual,
          baseline_none, model]
all_models_names = ['baseline_combination', 'baseline_version1',
                'baseline_version2', 'baseline_concatenationv1v2',
                'baseline_concatenationv2v1', 'baseline_manual', 'baseline_none',
                'random forest']

In [14]:
models_results = {}
for model, model_name in zip(models, all_models_names):
    models_results[model_name] = classifier_utils.ProjectsResults(model, projects, non_features_columns, training=False)

## Combination

In [15]:
models_names = ['baseline_combination', 'random forest']
classifier_utils.compare_models_per_class('Combination', models_results, models_names)

                  model  precision    recall  f1-score
0  baseline_combination   0.100855  1.000000  0.170993
1         random forest   0.580946  0.557375  0.552480

## Version 1

In [16]:
models_names = ['baseline_version1', 'random forest']
classifier_utils.compare_models_per_class('Version 1', models_results, models_names)

               model  precision    recall  f1-score
0  baseline_version1   0.519473  1.000000  0.649132
1      random forest   0.845934  0.868452  0.856048

## Version 2

In [17]:
models_names = ['baseline_version2', 'random forest']
classifier_utils.compare_models_per_class('Version 2', models_results, models_names)

               model  precision    recall  f1-score
0  baseline_version2   0.237367  1.000000  0.351846
1      random forest   0.746494  0.739228  0.740350

## ConcatenationV1V2

In [18]:
models_names = ['baseline_concatenationv1v2', 'random forest']
classifier_utils.compare_models_per_class('ConcatenationV1V2', models_results, models_names)

                        model  precision    recall  f1-score
0  baseline_concatenationv1v2   0.041066  1.000000  0.075335
1               random forest   0.786429  0.510038  0.593751

## ConcatenationV2V1

In [19]:
models_names = ['baseline_concatenationv2v1', 'random forest']
classifier_utils.compare_models_per_class('ConcatenationV2V1', models_results, models_names)

                        model  precision    recall  f1-score
0  baseline_concatenationv2v1   0.008445  1.000000  0.016695
1               random forest   0.766667  0.501984  0.541667

## Manual

In [20]:
models_names = ['baseline_manual', 'random forest']
classifier_utils.compare_models_per_class('Manual', models_results, models_names)

             model  precision    recall  f1-score
0  baseline_manual   0.118856  1.000000  0.204728
1    random forest   0.622234  0.561165  0.582043

## None

In [21]:
models_names = ['baseline_none', 'random forest']
classifier_utils.compare_models_per_class('None', models_results, models_names)

           model  precision    recall  f1-score
0  baseline_none   0.009719  1.000000  0.019112
1  random forest   0.250000  0.333333  0.285714